<?php
//require __DIR__ . '/../vendor/autoload.php';

use app\core\util\Report;

$report = Report::make('Demo Report', 'Admin')
    ->addColumns([
        'name' => 'Name',
        'amount' => 'Amount',
        'date' => 'Date',
    ])
    ->addRows([
        ['name' => 'Kamal', 'amount' => 1250.50, 'date' => '2026-08-29'],
        ['name' => 'Nimal', 'amount' => 900.00, 'date' => '2026-08-28'],
    ])
    ->addCalculation('Total', 'amount', 'SUM')
    ->addCalculation('Average', 'amount', 'AVG')
    ->setHeader('Demo Company')
    ->setFooter('Generated by Mandakini Framework');


$pdf = $report->pdf();

file_put_contents(__DIR__ . '/demo.pdf', $pdf);



header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="demo.pdf"');
header('Content-Length: ' . strlen($pdf));
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
header('Cache-Control: private, max-age=0, must-revalidate');
header('Pragma: public');

echo $pdf;
exit;