<?php
namespace app\controllers;
use app\core\Controller;
use app\core\util\Report;
use app\models\Student;
use app\core\Request;
class ReportController extends Controller {
    public function marksAction(): void {
        error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
    
        $report=Report::make('Student Marks Report','Admin')
            ->query(Student::query()->select(['students.full_name AS student_name','marks.class_name','marks.maths','marks.science','marks.english'])->join('marks','marks.student_id','=','students.id')->orderBy('marks.class_name')->orderBy('students.name'))
            ->addColumn('student_name','Student')
            ->addColumn('class_name','Class', ['align'=>'center'])
            ->addColumn('maths','Mathematics',['format'=>'integer','align'=>'right'])
            ->addColumn('science','Science',['format'=>'integer','align'=>'right'])
            ->addColumn('english','English',['format'=>'integer','align'=>'right'])
            ->groupBy('class_name')
            ->addGroupCalculation('Class Maths Total','maths','SUM')
            ->addCalculation('Maths Total','maths','SUM')
            ->addCalculation('Maths Average','maths','AVG')
            ->setPageSize('A4')->setPageOrientation('landscape')
            ->setHeader('ABC School')->setFooter('Generated by Mandakini MVC Framework')
            ->setStyles(['font_size'=>'10px','accent'=>'#333','header_background'=>'#eeeeee'])
            ->showPageNumbers(true);

        //header('Content-Type: application/pdf');
        //header('Content-Disposition: inline; filename="student-marks.pdf"');
        //echo $report->pdf();

        $pdf = $report->pdf();

file_put_contents(
    __DIR__ . '/student-marks-debug.pdf',
    $pdf
);

echo 'PDF size: ' . strlen($pdf) . ' bytes';
exit;
    }

    public function coursesAction(): void {
        $report=Report::make('Courses Report','Admin')
            ->query(\app\models\CourseOnWeb::query()->select(['course_id','course_name','course_instructor','course_duration','course_fee'])->orderBy('course_name'))
            ->addColumn('course_id','Course ID')
            ->addColumn('course_name','Course Name')
            ->addColumn('course_instructor','Instructor')
            ->addColumn('course_duration','Duration',['align'=>'center'])
            ->addColumn('course_fee','Fee',['format'=>'currency','align'=>'right'])
            ->setPageSize('A4')->setPageOrientation('portrait')
            ->setHeader('ABC School')->setFooter('Report by B.D.P. Niranjan')
            ->setStyles(['font_size'=>'10px','accent'=>'#333','header_background'=>'#eeeeee'])
            ->showPageNumbers(true);

        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="courses.pdf"');
        echo $report->pdf();
    }

    public function marksCsv(): never { $this->buildMarks()->download('csv','student-marks.csv'); }
    public function marksExcel(): never { $this->buildMarks()->download('excel','student-marks.xlsx'); }
    public function marksHtml(): never { $this->buildMarks()->download('html','student-marks.html'); }

    private function buildMarks(): Report {
        return Report::make('Student Marks Report','Admin')
            ->query(Student::query()->select(['students.name AS student_name','marks.class_name','marks.maths','marks.science','marks.english'])->join('marks','marks.student_id','=','students.id')->orderBy('marks.class_name')->orderBy('students.name'))
            ->addColumn('student_name','Student')->addColumn('class_name','Class',['align'=>'center'])
            ->addColumn('maths','Mathematics',['format'=>'integer','align'=>'right'])
            ->addColumn('science','Science',['format'=>'integer','align'=>'right'])
            ->addColumn('english','English',['format'=>'integer','align'=>'right'])
            ->groupBy('class_name')->addGroupCalculation('Class Maths Total','maths','SUM')->addCalculation('Maths Total','maths','SUM');
    }

    public function testPdfAction(Request $request) {


        $report = Report::make('Demo Report', 'Admin')
            ->addColumns([
                'name' => 'Name',
                'amount' => 'Amount',
                'date' => 'Date',
            ])
            ->addRows([
                ['name' => 'Kamal', 'amount' => 1250.50, 'date' => '2026-08-29'],
                ['name' => 'Nimal', 'amount' => 900.00, 'date' => '2026-08-28'],
            ])
            ->addCalculation('Total', 'amount', 'SUM')
            ->addCalculation('Average', 'amount', 'AVG')
            ->setHeader('Demo Company')
            ->setFooter('Report by B.D.P. Niranjan');


        $pdf = $report->pdf();

        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="demo.pdf"');
        header('Content-Length: ' . strlen($pdf));
        header('Content-Transfer-Encoding: binary');
        header('Accept-Ranges: bytes');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');

        echo $pdf;
        exit;

        //file_put_contents(__DIR__ . '/demo.pdf', $pdf);
        return $this->render('testPdf', ['pdf' => $pdf]);
    }
}
