<?php
$css = $styles['css'] ?? '';
$accent = $styles['accent'] ?? '#333333';
$headerBg = $styles['header_background'] ?? '#eeeeee';
$fontSize = $styles['font_size'] ?? '10px';
$logoData = $asset($logo);
?>
<!doctype html><html><head><meta charset="UTF-8">
<title><?= $escape($title) ?></title>
<style>
@page{margin:28px 30px 35px 30px}body{font-family:DejaVu Sans,Arial,sans-serif;font-size:<?= $escape($fontSize) ?>;color:#222;margin:0}.report-header{border-bottom:2px solid <?= $escape($accent) ?>;padding-bottom:10px;margin-bottom:14px}.brand{display:flex;align-items:center;gap:12px}.logo{max-height:55px;max-width:150px}.title{font-size:22px;font-weight:bold}.subtitle{font-size:12px;margin-top:4px;color:#555}.meta{font-size:8.5px;color:#666;margin-top:6px}table{width:100%;border-collapse:collapse;table-layout:fixed}thead{display:table-header-group}th,td{border:1px solid #ccc;padding:6px 7px;vertical-align:top;word-wrap:break-word}th{background:<?= $escape($headerBg) ?>;font-weight:bold}tbody tr:nth-child(even){background:<?= $stripedRows ? '#fafafa' : '#ffffff' ?>}.group-row{background:#e8e8e8!important;font-weight:bold}.group-total{background:#f3f3f3;font-weight:bold}.summary{margin-top:15px;border:1px solid #ddd;padding:10px}.summary-title{font-weight:bold;margin-bottom:6px}.footer{margin-top:18px;padding-top:8px;border-top:1px solid #ccc;font-size:8.5px;color:#666}.totals{margin-top:12px}.total-item{display:inline-block;margin-right:18px;padding:6px 10px;border:1px solid #ddd}.custom-css{<?= $css ?>}
</style>
</head>
<body>
<div class="report-header">
    <div class="brand"><?php if($logoData): ?>
        <img class="logo" src="<?= $escape($logoData) ?>">
        <?php endif; ?>
        <div><div class="title">
            <?= $escape($title) ?>
        </div><?php if($header): ?>
            <div class="subtitle">
                <?= nl2br($escape($header)) ?>
            </div>
        <?php endif; ?>
        </div></div>
        <?php if($showGeneratedMeta): ?>
            <div class="meta">
                Generated: <?= $escape($generated) ?> &nbsp; | &nbsp; Generated by: <?= $escape($generatedBy) ?>
            </div>
        <?php endif; ?>
    </div>
</div>
<table>
    <thead>
        <tr>
            <?php foreach($columns as $column): ?>
                <th style="text-align:<?= $escape($column['align'] ?? 'left') ?>;<?= $column['width'] !== null ? 'width:'.$escape((string)$column['width']).';' : '' ?>"><?= $escape($column['label']) ?></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
<?php if($hasGrouping): foreach($groups as $group): ?><tr class="group-row"><td colspan="<?= count($columns) ?>"><?= $escape($group['key']) ?></td></tr><?php foreach($group['rows'] as $row): ?><tr><?php foreach($columns as $column): ?><td style="text-align:<?= $escape($column['align'] ?? 'left') ?>;<?php foreach($cellStyle($row,$column) as $sk=>$sv): echo $escape($sk).':'.$escape($sv).';'; endforeach; ?>"><?= $escape($format($value($row,$column['key']),$column)) ?></td><?php endforeach; ?></tr><?php endforeach; ?><?php if($group['calculations']): ?><tr class="group-total"><td colspan="<?= count($columns)-1 ?>">Group total</td><td><?= $escape(json_encode($group['calculations'], JSON_UNESCAPED_UNICODE)) ?></td></tr><?php endif; ?><?php endforeach; else: foreach($rows as $row): ?><tr><?php foreach($columns as $column): ?><td style="text-align:<?= $escape($column['align'] ?? 'left') ?>;<?php foreach($cellStyle($row,$column) as $sk=>$sv): echo $escape($sk).':'.$escape($sv).';'; endforeach; ?>"><?= $escape($format($value($row,$column['key']),$column)) ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?>
</tbody>
</table>
<?php if($summary || $calculations): ?>
    <div class="summary">
        <div class="summary-title">Summary</div>
        <?php foreach($summary as $k=>$v): ?>
            <div><strong><?= $escape($k) ?>:</strong> <?= $escape($v) ?></div>
            <?php endforeach; ?>
            <?php foreach($calculations as $k=>$v): ?>
                <div><strong><?= $escape($k) ?>:</strong> <?= $escape($v) ?></div>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
<?php if($footer): ?>
    <div class="footer"><?= nl2br($escape($footer)) ?></div>
    <?php endif; ?>
</body>
</html>
